# 개정판 서문 {.unnumbered}

"R 을 활용한 데이터과학" 개정판에 오신 것을 환영합니다!
이번 개정판에서는 유용성이 떨어진 내용을 빼고, 초판에 포함되면 좋았을 내용을 추가하고, 텍스트와 코드를 업데이트하여, 베스트프랙티스를 수정하는 등 초판을 대대적으로 개편하였습니다.
그리고, Mine Çetinkaya-Rundel 가 공저자로 추가된 것은 기쁜 일입니다.
그는 유명한 데이터과학분야 교육자이고, Posit (구 RStudio) 의 동료입니다.

가장 큰 변경 사항을 간략히 요약하면 다음과 같습니다.

-   책의 첫 번째 파트는 "전체 그림"으로 이름이 변경되었습니다.
    이 섹션에서는 세부 사항으로 들어가기에 앞서 데이터과학의 "전체 그림"에 대한 대략적인 세부 사항을 제공하는 것입니다.

-   책의 두 번째 파트는 '시각화'입니다.
    이 부분에서는 데이터 시각화 도구와 모범 사례를 초판에 비해 더 자세히 다룹니다.
    자세한 정보들은 역시 [ggplot2 책](http://ggplot2-book.org/)에 있지만, R4DS는 가장 중요한 기술을 더 많이 다룹니다.

-   세 번째 파트는 이제 "변환"으로 불리며 수치형, 논리형 벡터 및 결측값에 대한 챕터가 새롭게 추가되었습니다.
    이전에는 데이터 변환 장의 일부였지만, 훨씬 더 많은 지면을 사용하여 모든 세부 사항을 다룹니다.

-   이 책의 네 번째 파트는 "불러오기"입니다.
    플랫텍스트 파일읽기 외에, 스프레드시트 작업, 데이터베이스에서 데이터 가져오기, 빅데이터 작업, 계층적 데이터 직사각형화, 웹 사이트에서 데이터 스크래핑 등 새로운 챕터가 추가되었습니다.

-   "프로그램" 파트는 그대로 유지되었지만, 가장 중요한 함수작성과 반복에 초점을 맞춰 처음부터 끝까지 다시 작성되었습니다.
    함수작성에는 tidyverse 함수를 래핑하는 방법 (타이디 평가의 문제를 다루면서)에 대한 자세한 내용이 포함되었습니다.
    이 방법은 지난 몇 년 동안 훨씬 쉬워지고 중요해졌기 때문입니다.
    외부 R 코드에서 볼 수 있는 중요한 기본 R 함수에 대한 새로운 장도 추가되었습니다.

-   모델링 파트는 빠졌습니다.
    모델링을 충분히 다루기에는 지면이 부족했고, 훨씬 좋은 리소스들이 많아졌습니다.
    막스 쿤Max Kuhn과 줄리아 실게Julia Silge의 [tidymodels](https://www.tidymodels.org/) 패키지와 [Tidy Modeling with R](https://www.tmwr.org/)웹사이트를 추천합니다.

-   의사소통 부분은 그대로 유지하되 R Markdown 대신 [콰르토(Quarto)](https://quarto.org/)로 완전히 업데이트되었습니다.
    이 책은 콰르토로 작성되었으며, 콰르토는 미래의 도구라고 확실히 말할 수 있습니다.
